<div>H1</div>
<div class="panel_support panel_support">
    <h3 class="action">Support</h3>
    <ul>
        <li><a href="#">Abouts Us</a></li>
        <li><a href="#">Contact Us</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">FAQ's</a></li>
    </ul>
</div>

<script type="text/x-magento-init">
        {
            ".panel_support ul": {
                    "mage/dropdown": {
                            "triggerTarget": ".panel_support .action",
                            "appendTo":".panel_support",
                            "timeout": "2000",
                            "closeOnMouseLeave": false,
                            "closeOnEscape": true,
                            "triggerClass":"active",
                            "parentClass":"active",
                            "buttons":[]
                    }
            }
        }

</script>
