<?php
$collection = $block->getManufacturerCollection();
?>
<h3>Manufacturer Show</h3>
<?php if(count($collection) > 0 ):?>
<div id="sow-brand" class="sow-owlcarousel">
        <div class="owl-carousel" data-manufacturer='<?php echo $block->getDataManufacturer()?>'>
            <?php foreach ($collection as $manufacturer): ?>
                 <div class="sow_item">
                     <a href="javascript:void(0)"><img src="<?php echo $manufacturer->getManufacturerUrl() ?>" alt="<?php echo $manufacturer->getManufacturerName() ?>"></a>
                 </div>
            <?php endforeach ?>
        </div>
</div>
<?php endif; ?>
