<?php
$title = $block->getOptions('widget_title');
$items = $block->getManufacturerCollection();
$size = array();
$size['width'] =100;
$size['height'] =100;

?>
<?php if(count($items) > 0 ): ?>
    <div class="sow-manufacturer sow-owlcarousel">
        <?php if ($title): ?>
            <div class="sow-title">
                <h3><span><?php /* @escapeNotVerified */
                        echo $title; ?></span></h3>
            </div>
        <?php endif ?>
        <div class="sow-content">
            <div class="sow-items owl-carousel" data-slider='<?php echo $block->getDataSlider() ?>'>
                <?php foreach ($items as $item): ?>
                    <div class="sow-item">
                        <div class="image">
                            <a href="<?php echo $item->getLink();?>"> <?php echo $item->getImage($size) ?></a>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
<?php endif?>