<a href="javascript:void(0)" id="to_top">Back to Top</a>

<script>
    require([
        'jquery',
    ], function ($) {
        'use strict';
        var scrollTime;
        $(window).scroll(function () {
            clearTimeout(scrollTime);
            scrollTime = setTimeout(function () {
                if (jQuery(this).scrollTop() > 100) {
                    $('#to_top').fadeIn();
                } else {
                    $('#to_top').fadeOut();
                }
            }, 200);
        });
        $('#to_top').click(function () {
            $('html, body').animate({scrollTop: 0}, 600);
        });
    })
</script>