<?php
$title = $block->getOptions('widget_title');
$items = $block->getInstagramCollection();
$size = array();
$size['width'] =100;
$size['height'] =100;

?>
<?php if(count($items) > 0 ): ?>
<div class="sow-instagram sow-owlcarousel">
    <?php if ($title): ?>
        <div class="sow-title">
            <h3><span><?php /* @escapeNotVerified */
                    echo $title; ?></span></h3>
        </div>
    <?php endif ?>
    <div class="sow-content">
        <div class="sow-items owl-carousel" data-slider='<?php echo $block->getDataSlider() ?>'>
            <?php foreach ($items as $item): ?>
            <div class="sow-item">
               <div class="image"><?php echo $item->getImage($size) ?></div>
                <div class="content"><?php echo $item->getInstagramContent() ?></div>
                <div class="name"><?php echo $item->getInstagramName() ?></div>
            </div>
            <?php endforeach ?>
        </div>
    </div>
</div>
<?php endif?>