<?php

$items = $block->getItems();

$html = $block->drawMenu($items, $parent_id = 0);

?>

<div id="sow_menu">
    <?php echo $html;?>
</div>


<script>
    require(['jquery'], function($){
        $('#sow_menu .open').on('click', function (e) {
                $(this).toggleClass('active').parent().children('.submenu').stop().slideToggle('medium');
        })
    });
    /* End Require*/
</script>