<?php
$items = $block->getMenuItem();
?>
<div id="sow_menu">
    <ul>
        <?php if ($items): ?>
            <?php foreach($items as $item):?>
                <li><?php echo $item->getItemName(); ?>
                    <!--     Submenu      -->
                    <?php if($subItems = $block->getSubItems($item->getItemId())):?>
                        <ul>
                        <?php foreach ($subItems as $subItem):?>
                        <li><?php echo $item->getItemName(); ?>

                        <?php endforeach;?>
                        </ul>
                    <?php endif;?>
                </li>

            <?php endforeach;?>
        <?php endif; /* End if ($items): */?>
    </ul>
</div>

<script>
    require(['jquery'], function($){
        $('#sow_menu .open').on('click', function (e) {
                $(this).toggleClass('active').parent().children('.submenu').stop().slideToggle('medium');
        })
    });
    /* End Require*/
</script>