<script type="text/javascript">
    require(
        ['jquery'],
        function ($) {

            var date = new Date();
            var id = 1234;
            date.setTime(date.getTime() + (1 * 24 * 60 * 60 * 1000));
            var expires = "; path=/; expires=" + date.toGMTString();
            console.log("warehouse_id=" + id + expires);
            // document.cookie = "warehouse_id=" + id + expires;
            document.cookie = 'warehouse_id' + '=1; path=/; expires=Thu, 01 Jan 1970 00:00:01 GMT;';
        });
</script>