<?php

$items = $block->getLv0Item();

//$html = $block->drawMenu($items, $parent_id = 0,$lv = 1);

?>
<?php if(false):?>
<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
       <?php foreach ($items as $item):?>

        <?php
            $subItems = $block->getchildItems($item['item_id']);
            $html = $block->drawSubMenu($subItems,$item['item_id'],2);
           ?>
            <li>
                <?php echo $item['item_name'];
                    echo $html;
                ?>
            </li>
        <?php endforeach; ?>
    </ul>
</nav>
<?php endif;?>

