<?php
$collection = $block->getTestimonialCollection();
?>
<h3>Testimonial Show</h3>
<?php if(count($collection) > 0 ):?>
<div id="sow-testimonial" class="sow-owlcarousel">
        <div class="owl-carousel" data-testimonial='<?php echo $block->getDataTestimonial()?>'>
            <?php foreach ($collection as $testimonial): ?>
                 <div class="sow_item">
                     <a href="javascript:void(0)"><img src="<?php echo $testimonial->getTestimonialUrl() ?>" alt="<?php echo $testimonial->getTestimonialName() ?>"></a>
                 </div>
            <?php endforeach ?>
        </div>
</div>
<?php endif; ?>
