<header id="header">
    <div class="panel-header">
        <?php echo $this->getChildHtml("skip_to_content"); ?>
        <?php echo $this->getChildHtml("header.links"); ?>
        <?php echo $this->getChildHtml("store_language"); ?>
    </div>
    <div class="header-content">
        <?php echo $this->getChildHtml("logo"); ?>

        <?php echo $this->getChildHtml("minicart"); ?>
        <?php echo $this->getChildHtml("top.search"); ?>
    </div>
    <?php echo $this->getChildHtml("navigation.sections"); ?>

</header>
