<?php
$config = $block->getPopupConfig();
$cookie_time = $config->getCookieTime();
?>
<?php if($config->getStatus()):?>
<div id="popup_newsletter" class="mfp-hide" style="background-image: <?php if($config->getBgImage()){echo $block->getBgImage();}else{echo "";}?>;
        background-position: center center;
        background-repeat: no-repeat;
        margin: 0 auto;
        width: <?php if($config->getWidth()){echo $config->getWidth().'px';}else{echo "700px";}?>;
        height: <?php if($config->getHeight()){echo $config->getHeight().'px';}else{echo "320px";}?>" data-cookie="<?php echo $cookie_time;?>">
    <div class="popup_news_close">X</div>
    <div class="popup_content">
        <?php if($config->getTitle()): ?>
        <div class="popup title">
            <h3><?php echo $config->getTitle() ?></h3>
        </div>
        <?php endif ?>
        <?php if($config->getDescription()): ?>
            <div class="popup description"><?php echo $config->getDescription() ?></div>
        <?php endif ?>
        <form action="<?php echo $block->getFormActionUrl()?>" method="POST">
            <div class="field newsletter">
                <div class="control">
                    <input name="email" type="email"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                </button>
            </div>
        </form>
    </div>
    <div class="subscribe-bottom">
        <input type="checkbox" id="dont_show_popup_news_again" name="dont_show_popup_news_again">
        <label for="dont_show_popup_news_again"><?php echo __("Don't show this popup again")?></label>
    </div>
</div>
<?php endif ?>